# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry

# C: This file was downloaded here: https://github.com/ckan/ckan/blob/master/contrib/docker/docker-compose.yml
ckan:
  container_name: ckan
  # Note, if you are working on CKAN core, change this to
  # build ../../
  image: ckan/ckan:latest
  links:
      - db
      - solr
      - redis
  ports:
      - "80:5000"
  volumes:
      - "./ckanext-temacultura:/usr/lib/ckan/default/src/ckanext-temacultura"
  environment:
      - DB_PORT_5432_TCP_ADDR=db
      - SOLR_PORT_8983_TCP_ADDR=solr
      - REDIS_PORT_6379_TCP_ADDR=redis

db:
  container_name: db
  image: ckan/postgresql
  
solr:
  container_name: solr
  image: ckan/solr:latest
    
redis:
  container_name: redis
  image: redis:latest
